/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;

import DAO.SucursalesDAORelacional;
import MODEL.Sucursales;
import javax.swing.ButtonModel;
import javax.swing.JOptionPane;

/**
 *
 * @author LuikFear
 */
public class ModS extends javax.swing.JFrame {

        
        
        
    int estado;
    int codigo = 0;
    int codigo_id = -1;
  
    
    int content;
            
        
    public ModS(Sucursales sucursales) {
        initComponents();
        cargar(sucursales);
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        JTcodigo = new javax.swing.JTextField();
        JTnombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        JTdireccion = new javax.swing.JTextField();
        JTcorreo = new javax.swing.JTextField();
        JTelefono = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));
        jPanel1.setForeground(new java.awt.Color(102, 102, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setText("Direccion");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel6.setText("Correo");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        JTcodigo.setEnabled(false);
        JTcodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTcodigoActionPerformed(evt);
            }
        });
        jPanel1.add(JTcodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 140, -1));
        jPanel1.add(JTnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 140, -1));

        jLabel2.setText("Codigo");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 56, -1, -1));

        jLabel3.setText("Nombre");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 94, -1, -1));

        jButton1.setText("Modificar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 116, 59));

        jLabel7.setText("Telefono");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Modificar Sucursal");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 20, -1, -1));

        jButton2.setText("Regresar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));
        jPanel1.add(JTdireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 150, 20));
        jPanel1.add(JTcorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 156, -1));
        jPanel1.add(JTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 156, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTcodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTcodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTcodigoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (JTcodigo.getText().isEmpty() && JTnombre.getText().isEmpty()
            && JTdireccion.getText().isEmpty() && JTcorreo.getText().isEmpty() && JTelefono.getText().isEmpty()  ) {
            JOptionPane.showMessageDialog(null, "Llena todos los campos");
        } else {
         

          enviarS();
           Main Newframe = new Main() ;
            Newframe.setVisible(true);
            dispose();

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        
        Main Newframe = new Main() ;
            Newframe.setVisible(true);
            dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    
       public void Mostrar(int codigo_id) {

        codigo = codigo_id;
        SucursalesDAORelacional sd = new SucursalesDAORelacional();

        Sucursales SU = sd.obtener_sucursal(codigo_id);

        JTcodigo.setText(SU.getCodigo()+ "");
        JTnombre.setText(SU.getNombre() + "");
        JTdireccion.setText(SU.getDireccion()+ "");
        JTcorreo.setText(SU.getCorreo()+ "");
        JTelefono.setText(SU.getTelefono()+ "");
        
        

    }
            
            
        private void enviarS() {


       Sucursales SU = new Sucursales(Integer.parseInt(JTcodigo.getText()), JTnombre.getText(), JTdireccion.getText(), JTcorreo.getText(), Integer.parseInt(JTelefono.getText()));
       SucursalesDAORelacional SUDAO = new SucursalesDAORelacional();
       SUDAO.modificar_sucursal(SU);


       }
            
     public void cargar(Sucursales sucursales) {
        JTcodigo.setText(String.valueOf(sucursales.getCodigo()));
        JTnombre.setText(sucursales.getNombre());
            JTdireccion.setText(sucursales.getDireccion());
       JTcorreo.setText(sucursales.getCorreo());
       JTelefono.setText(String.valueOf(sucursales.getTelefono()));
        
     
       
        codigo_id = sucursales.getCodigo();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JTcodigo;
    private javax.swing.JTextField JTcorreo;
    private javax.swing.JTextField JTdireccion;
    private javax.swing.JTextField JTelefono;
    private javax.swing.JTextField JTnombre;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}


